<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>fundamentos javascript</title>
    </head>

    <body>
        <h1>fundamentos javascript</h1>
        <script>
            try {
                console.log("el el Try se agrega el codigo a evaluar|");
                noexiste;
                console.log("segundo mensaje en el try");
            } catch(error) {
                console.log("catch, captura cualquier error surgido o lanzado en el Try");
            }finally{
                console.log("el bloque finally se ejecuta siempre al final de un bloque Try Catch");
            }



            try{
                let numero = 'y';
                if(isNaN(numero)){
                    throw new Error("no es numero");
                }
                console.log(numero * numero)
            }catch(error){
                console.log('se produjo el siguiente error: $(error)');
            }
        </script>
    </body>
    
</html>